### ISSUE TITLE
Can't create PDF

### ISSUE THREAD

**Issue by migarol** [venam/Form-PDF-Builder#1]
As a user, when i create my form and upload it to my webserver, i edit my fields and when i click on Create PDF, nothing happens, i don't see any error on log nor console.

Any Idea?

**Comment by venam** [comment]
Hello @migarol,
I think the issue you're having is when generating the HTML file after building the form and uploading/opening it with the browser.
It should be in the same directory as the rest of the project as it uses the files inside the /assets or just upload the assets to wherever you want to upload the PDF generation HTML.

Cheers!

**Comment by migarol** [comment]
Hey Venam,

I got that working, the real issue is generating the pdf after the form is
filled. Any ideas?
